server:
  port: 9089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  rabbitmq:
    host: localhost
    post: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled:ture
foo: foo version 1
